trigger:
- master

stages:
  
  - stage: pre_production

    jobs:
    - deployment: pre_production
      pool: Hosted Ubuntu 1604
      continueOnError: false
      timeoutInMinutes: 20
      environment: test-kubernetes

      strategy:
            runOnce:

              deploy:
                steps:
                
                - checkout: self
              
                - task: KubernetesManifest@0
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'test-kubernetes-tailwindtradersaksnjrrmmx4aqaso-test-kubernetes-1573429988669'
                    manifests: 'ops40/demos/manifest/azurevote.yml'

